event_ticketing/event_ticketing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('ticketapp.urls')),
]

event_ticketing/ticketapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.user_signup, name="user_signup"),
    path("login/", views.user_login, name="user_login"),
    path("logout/", views.user_logout, name="user_logout"),
    path("home/", views.home, name="home"),
    path("error/", views.error, name="error"),
    path("events/", views.events, name="events"),
    path("events/buy/<int:event_id>/", views.ticket, name="buy_ticket")
]

event_ticketing/ticketapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

ROLE_CHOICES = [
    ('organizer', 'organizer'),
    ('audience', 'audience'),
]

class CustomUser(AbstractUser):
    role = models.CharField(max_length=20, choices=ROLE_CHOICES)
    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
        related_name='custom_user_set',  # Add a custom related_name
        related_query_name='user',
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name='custom_user_set',  # Add a custom related_name
        related_query_name='user',
    )

class Event(models.Model):
    title = models.CharField(max_length=100)
    cost = models.CharField(max_length=20)
    location = models.CharField(max_length=100)
    date = models.DateField()

class Ticket(models.Model):
    event_title = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

event_ticketing/ticketapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import *
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("role", 'username', 'password1', 'password2')

class LoginForm(forms.Form):
    model = User
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('title', 'location', 'date', 'cost')

event_ticketing/ticketapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import *
from django.contrib.auth import get_user_model
def index(request):
    if not request.user.is_authenticated:
        return render(request, 'ticketapp/index.html')
    else:
        return redirect("home")

def error(request):
    return render(request, 'ticketapp/error.html')

def home(request):
    if request.user.is_authenticated:
        return render(request, 'ticketapp/home.html')
    else:
        return redirect("index")

def user_signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("home")
    else:
        form = SignupForm()

    return render(request, 'ticketapp/signup.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect("home")
            else:
                return redirect("error")
    else:
        form = LoginForm()

    return render(request, 'ticketapp/login.html', {"form": form})

@login_required
def user_logout(request):
    logout(request)
    return redirect('user_login')

@login_required
def events(request):
    events = Event.objects.all()

    if request.method == "POST":
        form = EventForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect("events")
    else:
        form = EventForm()

    return render(request, 'ticketapp/events.html', {'events': events, "form": form})


@login_required
def ticket(request, event_id):
    if request.method == "POST":
        event = Event.objects.get(id=event_id)
        user = get_user_model()
        Ticket.objects.create(event_title=event, user=user)
        return redirect('home')
    else:
        event = Event.objects.get(id=event_id)
        return render(request, 'ticketapp/events.html', {'event': event})

event_ticketing/ticketapp/templates/ticketapp/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ERROR</title>
</head>
<body>
  <style>
    h1 {
      font-size: 50px;
    }
  </style>
  <h1>error</h1>
</body>
</html>

event_ticketing/ticketapp/templates/ticketapp/events.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Events</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            text-align: center;
            margin-top: 100px;
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
        }
        h1 {
            color: #333;
        }
        a {
            padding: 10px 20px;
            margin: 10px;
            text-decoration: none;
            color: #fff;
            background-color: #007bff;
            border-radius: 5px;
            display: flex;
            justify-content: center;
            align-items: center;

        }
        a:hover {
            background-color: #0056b3;
        }
        .john {
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            margin-top: -5px;
            display: inline-block;
        }
        input[type="text"], input[type="password"] {
            width: 100%;
            padding: 10px;
            margin: 5px 0;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
        }
        .but {
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            background-color: #007bff;
            color: #fff;
            cursor: pointer;
        }
        .but:hover {
            background-color: #0056b3;
        }
        .main {
            background-color: #fff;
            padding-top: 10px;
            display: flex;
        }

        .event {
            background-color: #eeeeee;
            margin: 15px;
            border-radius: 10px;
            box-shadow: 2px 2px 2px 2px #dadada;
            height: 420px;
            width: 290px;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .ticket {
            display: flex;
            height: 55px;
        }

        h2 {
            width: 200px;
            display: flex;
            align-items: center;
            justify-content: center;
        }



    </style>
</head>
<body>
    <div class="main">
        {% if not events %}
        <h1>No Events</h1>
        {% else %}
            <div class="event">
                <h1>Events:</h1>
                {% for event in events %}
                        <div class="ticket">
                            <h2>{{ event.title }}</h2>
                            {% if request.user.role == "audience" %}
                                <form method="post" action="{% url 'buy_ticket' event.id %}">
                                    {% csrf_token %}
                                    <button type="submit">buy</button>
                                </form>
                            {% endif %}
                        </div>
                {% endfor %}
            </div>
        {% endif %}
        {% if request.user.role == "organizer" %}
        <div>
        <form class="john" method="post">
            <h1>Add Event</h1>
            {% csrf_token %}
            {{ form.as_p }}
            <button class="but" type="submit">Add Event</button>
        </form>
        {% endif %}
        </div>
    </div>
    <a href="{% url 'home' %}">home page</a>
</body>
</html>

event_ticketing/ticketapp/templates/ticketapp/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HOME-PAGE</title>
    <style>
        body {
            background-color: #f4f4f4;
            text-align: center;
            margin-top: 100px;
        }

        h1 {
            font-family: Arial, sans-serif;
            font-size: 20px;
        }

        a {
            display: inline-block;
            padding: 10px 20px;
            margin-top: 20px;
            text-decoration: none;
            color: #fff;
            background-color: #007bff;
            border-radius: 5px;
        }
        a:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <h1>Welcome, {{ request.user.username }}</h1>
    <h1>You are assigned as "{{ request.user.role }}"</h1>
    <a href="{% url 'events' %}">Events</a>
    <a href="{% url 'user_logout' %}">Logout</a>
</body>
</html>

event_ticketing/ticketapp/templates/ticketapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AUTHORIZATION</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            text-align: center;
            margin-top: 100px;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        h1 {
            color: #333;
        }
        a {
            display: inline-block;
            padding: 10px 20px;
            width: 50px;
            margin: 10px;
            text-decoration: none;
            color: #fff;
            background-color: #007bff;
            border-radius: 5px;
        }
        a:hover {
            background-color: #0056b3;
        }
        .author {
            background-color: #fff;
            box-shadow: 2px 2px 2px 2px #e8e8e8;
            padding: 20px;
            border-radius: 10px;
        }
    </style>
</head>
<body>
    <div class="author">
            <h1>Welcome.</h1>
            <a href="{% url 'user_signup' %}">Signup</a>
            <a href="{% url 'user_login' %}">Login</a>
    </div>
</body>
</html>

event_ticketing/ticketapp/templates/ticketapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LOGIN</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            text-align: center;
            margin-top: 100px;
        }
        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            display: inline-block;
        }
        input[type="text"], input[type="password"] {
            width: 100%;
            padding: 10px;
            margin: 5px 0;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
            background-color: #e8f0fe;
        }
        button[type="submit"] {
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            background-color: #007bff;
            color: #fff;
            cursor: pointer;
        }
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
        p {
            margin-top: 10px;
            color: #666;
        }
        a {
            text-decoration: none;
            color: #007bff;
        }
        a:hover {
            text-decoration: underline;
        }
        h1 {
            color: #2a3136;
            margin-bottom: 35px;
        }
    </style>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <h1>Login</h1>
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
    <p>Don't have an account? <a href="{% url 'user_signup' %}">Signup</a></p>
</body>
</html>

event_ticketing/ticketapp/templates/ticketapp/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SIGNUP</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            text-align: center;
            margin-top: 100px;
        }
        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            display: inline-block;
        }
        .form-group {
            margin-bottom: 15px;
            text-align: left;
        }
        label {
            display: block;
            margin-bottom: 5px;
        }
        input[type="text"], input[type="password"], select {
            width: 350px;
            height: 35px;
            padding: 10px;
            margin: 5px 0;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
            background-color: #e8f0fe;

        }
        button[type="submit"] {
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            background-color: #007bff;
            color: #fff;
            cursor: pointer;
        }
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
        p {
            margin-top: 10px;
            color: #666;
        }
        a {
            text-decoration: none;
            color: #007bff;
        }
        a:hover {
            text-decoration: underline;
        }
        h1{
            color: #2a3136;
        }
    </style>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <h1>Signup</h1>
        <div class="form-group">
            <label for="id_role">Role:</label>
            {{ form.role }}
        </div>
        <div class="form-group">
            <label for="id_username">Username:</label>
            {{ form.username.errors }}
            {{ form.username }}
        </div>
        <div class="form-group">
            <label for="id_password1">Password:</label>
            {{ form.password1.errors }}
            {{ form.password1 }}
        </div>
        <div class="form-group">
            <label for="id_password2">Confirm Password:</label>
            {{ form.password2.errors }}
            {{ form.password2 }}
        </div>
        <button type="submit">Signup</button>
    </form>
    <p>Already have an account? <a href="{% url 'user_login' %}">Login</a></p>
</body>
</html>